### ISSUE TITLE
How to add this library as a dependency in an Android project

### ISSUE THREAD

**Issue by AkritiSondhi** [dsprenkels/sss#14]
I wish to use the Java binding of the library for an Android project, but I cannot find a maven dependency for it. Can you please provide the maven dependency for it?

Also, I'm unable to compile the Android code I cloned from the library. So, can you also provide the steps, to integrate and use the library for an android project.

**Comment by dsprenkels** [comment]
Hey @AkritiSondhi, thanks for showing interest in this library.

[As is the case with Swift](https://github.com/dsprenkels/sss/issues/13), I am not ~very~ at all experienced with Android development. I made the JNI bindings as is, and have only tested them on my phone. I'm already sorry for the bad support, but I will try my best.

I have not put the library on any package manager (just because I do not yet know how the Android build system seems to work). I would recommend using [JitPack](https://jitpack.io/) instead. They provide an example at https://jitpack.io/docs/. Translating this to `sss-android` should probably give something like:

```gradle
    allprojects {
        repositories {
            jcenter()
            maven { url "https://jitpack.io" }
        }
   }
   dependencies {
        compile 'com.github.dsprenkels:sss-android:master-SNAPSHOT'
   }
```

Note that to compile native code you additionally need the `CMake`, `LLDB` and `NDK` tools. On Arch Linux, you will probably run into [this problem](https://stackoverflow.com/q/40696961/5207081) which can be solved by installing [ncurses5-compat-libs](https://aur.archlinux.org/packages/ncurses5-compat-libs/) from the AUR.

This will maybe not solve everything, but should probably get you started. Please, if you can spare the effort, tell me if it works properly. Then I can write a proper `README.md` file in the [sss-android repo](https://github.com/dsprenkels/sss-android). Thanks in advance!

**Comment by dsprenkels** [comment]
I'm currently looking at the [Gradle user guide](https://docs.gradle.org/current/userguide/dependency_management_for_java_projects.html#sec:publishing_artifacts_java_tutorial) (thanks @yorickvP). It looks like it's not very hard to just make a Maven package. I could do this, but the code is not really mature yet and I would like to keep the option to make the project compatible with "normal" Java programs and rename it to `sss-java`.

**Comment by jaromil** [comment]
It may be of help, as a hint or alternative solution, to have a look at what we do with Zenroom which uses this library as entropy generator (seed) for a cryptographically secure RNG. Here are the build instructions also pointing to scripts https://github.com/DECODEproject/zenroom/wiki/Build. Beware that including Zenroom may be overhead (~1MB payload) if only randombytes is really needed.

**Comment by dsprenkels** [comment]
Closing as a stale issue.
